#!/bin/bash

# validate input:
# argument must be an integer...
if [[ $1 =~ ^[1-9]+$ ]]
then
	totalFarts=$1
elif [[ $1 == '' ]]
then
	# echo "Empty param"
	totalFarts=1
else
	echo "You must provide a single integer greater than 0"
	echo "how can i fart '$1' times??"
	exit -1
fi

# the following line was extracted from:
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
# stores the path where this script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
# turn the output of ls into an array
farts=(`ls $DIR/fart*`)

randomFart(){
	# pick a random number between 0 and the number of items in the list-1
	echo $RANDOM%${#farts[@]}
}


# store the kernel name
OS=`uname -s`

# use aplay on linux
if [[ $OS -eq 'Linux' ]]
then
	for i in `seq 1 $totalFarts`
		do
			rand=$(randomFart)
			aplay ${farts[$rand]}
		done
# and afplay on mac
else
	for i in `seq 1 $totalFarts`
		do
			rand=$(randomFart)
			afplay ${farts[$rand]}
		done
fi
