#!/bin/bash
# the following line was extracted from:
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
# stores the path where this script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
# turn the output of ls into an array
farts=(`ls $DIR/fart*`)
# pick a random number between 0 and the number of items in the list-1
rand=$(($RANDOM%${#farts[@]}))

# store the kernel name
OS=`uname -s`

# use aplay on linux
if [[ OS -eq 'Linux' ]]
then
	aplay ${farts[$rand]}
# and afplay on mac
else
	afplay ${farts[$rand]}
fi
